In [1]:
import numpy as np

In [2]:
with open("day13.txt", "r") as f:
    lines = f.readlines()
    lines = [l.rstrip() for l in lines]
    holes = [x for x in lines if "," in x]
    holes = [x.split(",") for x in holes]
    holes = [(int(y),int(x)) for x,y in holes]
    fold = [x.split(" ")[-1] for x in lines if "fold" in x]
    fold = [x.split("=") for x in fold]
    
    xmax = [x for x,y in holes]
    xmax = max(xmax)+1
    
    ymax = [y for x,y in holes]
    ymax = max(ymax)+1

In [3]:
def poke_paper(paper, holes):
    for h in holes:
        paper[h]+=1
    return paper

In [17]:
def fold_y(paper, lineno):
    for i, j in zip(reversed(range(lineno)), range(lineno+1,lineno*2+1 )):
        try:
            paper[i, :]+=paper[j,:]
        except:
            pass
    
    return paper[:lineno,:]

def fold_x(paper, lineno):
    for i, j in zip(reversed(range(lineno)), range(lineno+1,lineno*2+1 )):
        try:
            paper[:,i]+=paper[:,j]
        except:
            pass
        
    return paper[:,:lineno]

In [12]:
### part 1 
paper = np.zeros((xmax,ymax))
paper = poke_paper(paper, holes)

firstfold = fold[0]
axis = firstfold[0]
num = int(firstfold[1])
if axis=="y":
    paper = fold_y(paper, num)
elif axis=="x":
    paper = fold_x(paper, num)
    
paper[paper>0].shape[0]

684

In [24]:
paper = np.zeros((xmax,ymax))
paper = poke_paper(paper, holes)

for f in fold:
    axis = f[0]
    num = int(f[1])
    if axis=="y":
        paper = fold_y(paper, num)
    elif axis=="x":
        paper = fold_x(paper, num)

In [35]:
prior=0
for i in range(5,45, 5):
    print(paper[:,prior:i])
    prior=i

[[0. 0. 5. 4. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 4. 0.]
 [7. 0. 0. 1. 0.]
 [0. 3. 2. 0. 0.]]
[[ 3. 11.  2.  0.  0.]
 [ 2.  0.  0. 14.  0.]
 [ 5.  0.  0.  2.  0.]
 [ 2.  7.  8.  0.  0.]
 [ 3.  0. 23.  0.  0.]
 [12.  0.  0.  5.  0.]]
[[ 5.  4.  6.  9.  0.]
 [ 0.  0.  0. 14.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0. 27.  0.  0.  0.]
 [12.  0.  0.  0.  0.]
 [ 6. 23.  5.  9.  0.]]
[[ 2.  2. 12.  0.  0.]
 [ 3.  0.  0. 12.  0.]
 [14.  9. 18.  0.  0.]
 [24.  0.  0. 15.  0.]
 [10.  0.  0.  1.  0.]
 [18.  5. 32.  0.  0.]]
[[11.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [19.  0.  0.  0.  0.]
 [10.  0.  0.  0.  0.]
 [ 3. 14. 16.  1.  0.]]
[[ 0.  4.  2.  0.  0.]
 [ 8.  0.  0.  5.  0.]
 [10.  0.  0.  0.  0.]
 [ 2.  0. 19.  7.  0.]
 [ 9.  0.  0.  2.  0.]
 [ 0.  8.  9. 16.  0.]]
[[ 2.  0.  0.  8.  0.]
 [ 3.  0. 13.  0.  0.]
 [11.  9.  0.  0.  0.]
 [ 9.  0.  5.  0.  0.]
 [ 8.  0.  6.  0.  0.]
 [19.  0.  0.  2.  0.]]
[[ 3.  0.  0.  4.  0.]
 [13.  0.  0. 17.  0.]
 [ 8. 25. 2